---
abstract: 'A very easy interface to YouTube.'
author:
  - 'Daniel "Trizen" Șuteu <trizenx@gmail.com>'
build_requires:
  Test::More: '0'
configure_requires:
  Module::Build: '0'
dynamic_config: 1
generated_by: 'Module::Build version 0.4214, CPAN::Meta::Converter version 2.150005'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: WWW-YoutubeViewer
provides:
  WWW::YoutubeViewer:
    file: lib/WWW/YoutubeViewer.pm
    version: '0.06'
  WWW::YoutubeViewer::Activities:
    file: lib/WWW/YoutubeViewer/Activities.pm
    version: '0.01'
  WWW::YoutubeViewer::Authentication:
    file: lib/WWW/YoutubeViewer/Authentication.pm
    version: '0.01'
  WWW::YoutubeViewer::Channels:
    file: lib/WWW/YoutubeViewer/Channels.pm
    version: '0.01'
  WWW::YoutubeViewer::CommentThreads:
    file: lib/WWW/YoutubeViewer/CommentThreads.pm
    version: '0.01'
  WWW::YoutubeViewer::GetCaption:
    file: lib/WWW/YoutubeViewer/GetCaption.pm
    version: '0.02'
  WWW::YoutubeViewer::GuideCategories:
    file: lib/WWW/YoutubeViewer/GuideCategories.pm
    version: '0.01'
  WWW::YoutubeViewer::Itags:
    file: lib/WWW/YoutubeViewer/Itags.pm
    version: '0.04'
  WWW::YoutubeViewer::ParseJSON:
    file: lib/WWW/YoutubeViewer/ParseJSON.pm
    version: '0.01'
  WWW::YoutubeViewer::ParseXML:
    file: lib/WWW/YoutubeViewer/ParseXML.pm
    version: '0.04'
  WWW::YoutubeViewer::PlaylistItems:
    file: lib/WWW/YoutubeViewer/PlaylistItems.pm
    version: '0.01'
  WWW::YoutubeViewer::Playlists:
    file: lib/WWW/YoutubeViewer/Playlists.pm
    version: '0.01'
  WWW::YoutubeViewer::RegularExpressions:
    file: lib/WWW/YoutubeViewer/RegularExpressions.pm
    version: '0.01'
  WWW::YoutubeViewer::Search:
    file: lib/WWW/YoutubeViewer/Search.pm
    version: '0.01'
  WWW::YoutubeViewer::Subscriptions:
    file: lib/WWW/YoutubeViewer/Subscriptions.pm
    version: '0.01'
  WWW::YoutubeViewer::Utils:
    file: lib/WWW/YoutubeViewer/Utils.pm
    version: '0.02'
  WWW::YoutubeViewer::VideoCategories:
    file: lib/WWW/YoutubeViewer/VideoCategories.pm
    version: '0.01'
  WWW::YoutubeViewer::Videos:
    file: lib/WWW/YoutubeViewer/Videos.pm
    version: '0.01'
recommends:
  JSON::XS: '0'
  LWP::UserAgent::Cached: '0'
  Mozilla::CA: '0'
  Term::ReadLine::Gnu::XS: '0'
requires:
  Data::Dump: '0'
  Encode: '0'
  File::Path: '0'
  File::ShareDir: '0'
  File::Spec: '0'
  File::Spec::Functions: '0'
  Getopt::Long: '0'
  Gtk2: '0'
  HTTP::Request: '0'
  JSON: '0'
  LWP::Protocol::https: '0'
  LWP::UserAgent: '0'
  List::Util: '0'
  MIME::Base64: '0'
  Term::ANSIColor: '0'
  Term::ReadLine: '0'
  Text::ParseWords: '0'
  Text::Wrap: '0'
  URI::Escape: '0'
resources:
  license: http://dev.perl.org/licenses/
version: '0.06'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
