---
abstract: 'A very easy interface to YouTube.'
author:
  - 'Daniel "Trizen" Șuteu <trizenx@gmail.com>'
build_requires:
  Test::More: '0'
configure_requires:
  Module::Build: '0'
dynamic_config: 1
generated_by: 'Module::Build version 0.4211, CPAN::Meta::Converter version 2.150001'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: WWW-YoutubeViewer
provides:
  WWW::YoutubeViewer:
    file: lib/WWW/YoutubeViewer.pm
    version: '0.06'
  WWW::YoutubeViewer::GetCaption:
    file: lib/WWW/YoutubeViewer/GetCaption.pm
    version: '0.02'
  WWW::YoutubeViewer::Itags:
    file: lib/WWW/YoutubeViewer/Itags.pm
    version: '0.04'
  WWW::YoutubeViewer::ParseXML:
    file: lib/WWW/YoutubeViewer/ParseXML.pm
    version: '0.04'
  WWW::YoutubeViewer::RegularExpressions:
    file: lib/WWW/YoutubeViewer/RegularExpressions.pm
    version: '0.01'
  WWW::YoutubeViewer::Utils:
    file: lib/WWW/YoutubeViewer/Utils.pm
    version: '0.02'
recommends:
  Term::ReadLine::Gnu::XS: '0'
  XML::Fast: '0'
requires:
  Data::Dump: '0'
  File::Path: '0'
  File::Spec::Functions: '0'
  Getopt::Long: '0'
  HTTP::Request: '0'
  LWP::UserAgent: '0'
  Term::ANSIColor: '0'
  Term::ReadLine: '0'
  Text::ParseWords: '0'
  Text::Wrap: '0'
  URI::Escape: '0'
resources:
  license: http://dev.perl.org/licenses/
version: '0.06'
